# Generated by Django 5.0.1 on 2024-02-06 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='pharmacist',
        ),
        migrations.AddField(
            model_name='medicine',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_person',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.deliveryperson'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('pharmacy_owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pharmacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacy_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.pharmacist'),
            preserve_default=False,
        ),
    ]
