# Generated by Django 5.0.1 on 2024-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_pharmacy_pharmacist_medicine_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='pharmacy_owned',
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='legal_document',
            field=models.ImageField(blank=True, null=True, upload_to='legal_docs/'),
        ),
    ]
