# Generated by Django 5.0.1 on 2024-02-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_pharmacist_pharmacy_owned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='customer',
            new_name='sender_user',
        ),
    ]
