# Generated by Django 5.0.1 on 2024-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_customer_message_sender_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('medicine', 'medicine'), ('device', 'device'), ('nutritional', 'nutritional')], max_length=100),
        ),
    ]
