# Generated by Django 5.0.1 on 2024-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='unit',
            field=models.CharField(default='1kg', max_length=100),
            preserve_default=False,
        ),
    ]
