# Generated by Django 5.0.1 on 2024-02-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_medicine_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='form',
        ),
    ]
