# Generated by Django 5.0.1 on 2024-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_medicine_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
