# Generated by Django 5.0.1 on 2024-02-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
