# Generated by Django 5.0.1 on 2024-02-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_medicine_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
