# Generated by Django 5.0.1 on 2024-02-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=100),
        ),
    ]
